airpoll<-source("c:\\allwork\\rsplus\\chap2airpoll.dat")$value
#
#
attach(airpoll)
#
#
#
par(mfrow=c(2,2,))
par(pty="s")
plot(SO2,Mortality,pch=1,lwd=2)
title("(a)",lwd=2)
plot(SO2,Mortality,pch=1,lwd=2)
abline(lm(Mortality~SO2),lwd=2)
title("(b)",lwd=2)
airpoll1<-jitter(cbind(SO2,Mortality))
plot(airpoll1[,1],airpoll1[,2],xlab="SO2",ylab="Mortality",pch=1,lwd=2)
title("(c)",lwd=2)
plot(SO2,Mortality,pch=1,lwd=2)
rug(jitter(SO2),side=1)
rug(jitter(Mortality),side=2)
title("(d)",lwd=2)
#
names<-abbreviate(row.names(airpoll))
par(mfrow=c(1,1))
plot(SO2,Mortality,lwd=2,type="n")
text(SO2,Mortality,labels=names,lwd=2)
#
#
dev.off()
#
par(fig=c(0,0.7,0,0.7))
plot(SO2,Mortality,lwd=2)
abline(lm(Mortality~SO2),lwd=2)
lines(lowess(SO2,Mortality),lwd=2)
par(fig=c(0,0.7,0.65,1),new=TRUE)
#
hist(SO2,lwd=2)
par(fig=c(0.65,1,0,0.7),new=TRUE)
boxplot(Mortality,lwd=2)
#
dev.off()
#
hull<-chull(SO2,Mortality)
plot(SO2,Mortality,pch=1)
polygon(SO2[hull],Mortality[hull],density=15,angle=30)
cor(SO2,Mortality)
cor(SO2[-hull],Mortality[-hull])
#
dev.off()
#
chiplot(SO2,Mortality,vlabs=c("SO2","Mortality"))
#
dev.off()
#
bvbox(cbind(SO2,Mortality),xlab="SO2",ylab="Mortality")
#
bvbox(cbind(SO2,Mortality),xlab="SO2",ylab="Mortality",method="O")
#
#
h2d<-hist2d(SO2,Mortality)
persp(h2d,xlab="SO2",ylab="Mortality",zlab="Frequency")
#
#
den1<-bivden(SO2,Mortality)
persp(den1$seqx,den1$seqy,den1$den,xlab="SO2",ylab="Mortality",
zlab="Density",lwd=2)
#
plot(SO2,Mortality)
contour(den1$seqx,den1$seqy,den1$den,lwd=2,nlevels=20,add=TRUE)
#
plot(SO2,Mortality,pch=1,lwd=2,ylim=c(700,1200),xlim=c(-5,300))
symbols(SO2,Mortality,circles=Rainfall,inches=0.4,add=TRUE,lwd=2)
#
pairs(airpoll)
#
pairs(airpoll,panel=function(x,y) {abline(lsfit(x,y)$coef,lwd=2)
                                  lines(lowess(x,y),lty=2,lwd=2)
                                  points(x,y)})

#
coplot(Mortality~SO2|Popden)
#
coplot(Mortality~SO2|Popden,panel=function(x,y,col,pch)
 panel.smooth(x,y,span=1))
#


